# -*- coding: utf-8 -*-

MING_ADMIN = 'moyitian90@163.com'

SECRET_KEY = 'H\xe0z\xadR\x03\xab\xeb\xd0\x14\xae\xe9\xab\xcd2\xf3\x8dHC\xc4\x04k\x92\x18'
SQLALCHEMY_DATABASE_URI = 'mysql://root:feng@localhost:3306/ming'
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_RECORD_QUERIES = True
MING_POSTS_PER_PAGE = 10
MING_COMMENTS_PER_PAGE = 20
MING_FOLLOWERS_PER_PAGE = 20
